---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations: 
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: ConsulResolver
      name: consul-dc1
      address: consul-consul-server:8500
      datacenter: dc1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 8443
      name: https
  selector:
    service: ambassador
